# Generated by Django 6.0.1 on 2026-01-31 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_project_supervisor_task_priority_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Enseignant superviseur du projet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="Étudiant propriétaire du projet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
