# Generated by Django 6.0.1 on 2026-02-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_activitylog_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("project_created", "Projet créé"),
                    ("project_updated", "Projet modifié"),
                    ("task_created", "Tâche créée"),
                    ("task_updated", "Tâche modifiée"),
                    ("comment_added", "Commentaire ajouté"),
                    ("milestone_created", "Jalon créé"),
                    ("milestone_updated", "Jalon modifié"),
                    ("sprint_created", "Sprint créé"),
                    ("sprint_updated", "Sprint modifié"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("in_progress", "En cours"),
                            ("done", "Terminé"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("goal", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planifié"),
                            ("active", "Actif"),
                            ("completed", "Terminé"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
