# Generated by Django 6.0.1 on 2026-02-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_deliverable_submission_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Fichier déposé (PDF, etc.)",
                null=True,
                upload_to="submissions/%Y/%m/",
            ),
        ),
    ]
