# Generated by Django 6.0.1 on 2026-02-01 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_submission_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("project_created", "Projet créé"),
                    ("project_updated", "Projet modifié"),
                    ("task_created", "Tâche créée"),
                    ("task_updated", "Tâche modifiée"),
                    ("comment_added", "Commentaire ajouté"),
                    ("milestone_created", "Jalon créé"),
                    ("milestone_updated", "Jalon modifié"),
                    ("sprint_created", "Sprint créé"),
                    ("sprint_updated", "Sprint modifié"),
                    ("deliverable_created", "Livrable créé"),
                    ("submission_created", "Dépôt créé"),
                    ("review_submitted", "Revue envoyée"),
                    ("supervision_request_sent", "Demande de supervision envoyée"),
                    ("supervision_request_accepted", "Demande de supervision acceptée"),
                    ("supervision_request_declined", "Demande de supervision refusée"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SupervisionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("declined", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Message optionnel de l'étudiant"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True,
                        help_text="Message du superviseur (refus ou confirmation)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervision_requests",
                        to="core.project",
                    ),
                ),
                (
                    "requested_supervisor",
                    models.ForeignKey(
                        help_text="Enseignant à qui la demande est envoyée",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervision_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("project", "requested_supervisor"),
                        name="unique_pending_supervision_request_per_project_supervisor",
                    )
                ],
            },
        ),
    ]
