# Generated by Django 6.0.1 on 2026-02-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_supervision_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Sprint auquel la tâche est rattachée (optionnel).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.sprint",
            ),
        ),
    ]
